services:
  - type: web
    name: energy-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd webapp && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: DB_HOST
        fromDatabase:
          name: energy-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: energy-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: energy-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: energy-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: energy-db
          property: database

databases:
  - name: energy-db
    databaseName: energy
    user: energyuser
